import Banner from "@/components/pages/homeTwo/Banner";
import PopularOnlineStation from "@/components/pages/homeTwo/PopularOnlineStation";
import PopularRadioStation from "@/components/pages/homeTwo/PopularRadioStation";
import PopularShow from "@/components/pages/homeTwo/PopularShow";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home Two | Online Radio NextJs Template",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <Banner />
      <PopularOnlineStation />
      <PopularRadioStation />
      <PopularShow />
      {/* <Sponsor /> */}

      {/* <Latestblog /> */}
    </>
  );
};

export default page;
