"use client";
import "@/app/globals.css";
import Footer from "@/components/shared/Footer";
import NavBar from "@/components/shared/navbar/NavBar";
import "bootstrap/dist/css/bootstrap.min.css";
import type { Metadata } from "next";
import { usePathname } from "next/navigation";
import { Suspense, useEffect } from "react";
import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";
import "../styles/lib/all.min.css";
import "../styles/lib/remixicon.css";
import "../styles/scss/style.scss";
import Loading from "./loading";

export const metadata: Metadata = {
  title: "Home | Online Radio NextJs Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();

  useEffect(() => {
    import("bootstrap/dist/js/bootstrap");
  }, []);

  const pathName = usePathname();
  return (
    <html lang="en">
      <body>
        <NavBar />
        <Suspense fallback={<Loading />}>
          <main className="site-body">{children}</main>
        </Suspense>

        <div className="scroll-top">
          <a href="#">
            <i className="ri-arrow-up-line"></i>
          </a>
        </div>
        <Footer />
      </body>
    </html>
  );
}
